version: '3.8'

services:
  naverblog-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NAVER_ID=${NAVER_ID}
      - NAVER_SECRET=${NAVER_SECRET}
    volumes:
      - ./data.db:/app/data.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/branches"]
      interval: 30s
      timeout: 10s
      retries: 3
